- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: ELASTICSEARCH_API
  value: "http://elasticsearch.geonetwork.svc.cluster.local:9200/"
- key: NODE_ENV
  value: "dev"
- key: PORT
  value: "80"
- AZURE_KEYVAULT_URL:
  value: "https://sndadpinfvt3401.vault.azure.net/"
- APPINSIGHTS_SECRET_NAME:
  value: "ncea-frontend-APPINSIGHTS-CONNECTIONSTRING"