#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^ffc-wq$ --format={{.Name}})" ]; then
  echo "Creating ffc-wq Docker network"
  docker network create ffc-wq
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

docker-compose \
  -f docker-compose.yaml \
  -f docker-compose.override.yaml \
  up $@
